// Code generated by "stringer -type=Type"; DO NOT EDIT.

package go_engine_io_parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Open-0]
	_ = x[Close-1]
	_ = x[Ping-2]
	_ = x[Pong-3]
	_ = x[Message-4]
	_ = x[Upgrade-5]
	_ = x[Noop-6]
	_ = x[Error-7]
}

const _Type_name = "OpenClosePingPongMessageUpgradeNoopError"

var _Type_index = [...]uint8{0, 4, 9, 13, 17, 24, 31, 35, 40}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
